### ISSUE TITLE
add support for four-eyes principle to image signing

### ISSUE THREAD

**Issue by PeterPawn** [PeterPawn/YourFritz#1]
- add another (optional) layer of security to signed files, ensuring that the resulting ./var/signature file is signed again by at least two different persons, identified by a X.509 certificate or a OpenPGP certificate
- OpenPGP support needs additional packages
- try to keep the format of a signed image file compatible with vendors firmware, if it's possible - even if this firmware may be unable to verify the signature, it should still be usable to download and/or unpack it

**Comment by PeterPawn** [comment]
- not necessary anymore
- closed at this time, may be considered as an option later again

**Comment by doak** [comment]
> not necessary anymore

Would be nice to to know why it is "not necessary anymore" ;)

**Comment by PeterPawn** [comment]
The idea was a format, where at least two instances check a file, that provides extensions as a "plugin" and sign it with their own (secret) keys to stand with their "good name" for a valid and "harmless" extension.

Later (or little less than two years later) I've decided (driven by the lack of other developers, who take part here yet), that my own signing should be sufficient. The second point ("may be considered again later") may get a new focus, if the mentioned "second person" arrives "on stage" in the future.

Without the second author there's no need for "double signing" and the main intention for the "assembled chunks of code" is still, to solve the tasks, which are linked to the proclamated goal of this project - a framework for dynamic firmware extensions.

Any "secondary usability" is only a (welcomed) side-effect - there's no reason to invest time in a solution, that is not needed here and may be useful only in other projects.

**Comment by PeterPawn** [comment]
And I forgot to mention: This issue was linked to the original "signimage" solution. At the time, I was closing this issue, I was switching from "POSIX shell based scripts" to a more flexible (in my opinion) implementation based on PowerShell Core, which had gotten available (and really usable) at this time. And it provides (due to the supported platforms - with one single-package installation on Linux, BSD and MacOS X and it's always available in Windows - at least starting from W10) a much more "convenient" way to implement a common solution for a wider range of "hosts".

**Comment by doak** [comment]
@PeterPawn, thanks a lot for the explanation.

Thanks also for the link to [**PowerShell ***Core*****](https://github.com/powershell/powershell), which I was not aware of. Since I got far away from Windows for some time now, I did not even think once that something named *Power Shell* could be cross platform ;)
