### ISSUE TITLE
Toolbox error

### ISSUE THREAD

**Issue by YannisHeine** [PeterPawn/YourFritz#15]
Hey,

ich habe eine FritzBox 6490. Ich wollte darauf gerne ein SIAB image spielen.
Leider gibt es kein Fertiges also wollte ich eins mit Hilfe deiner YourFritz Toolbox erstellen.

Leider bekomme ich bei dem Command 

`TOOLBOX_IMAGE_SIZE=3 ./build_shellinabox_implant_image FRITZ.Box_6490_Cable.de-en-es-it-fr-pl.141.06.87.image > SIAB-6490.image`

folgenden Fehler 

```
tar: ./var/chksum.x86\n./var/chksum: Nicht im Archiv gefunden.
tar: Beende mit Fehlerstatus aufgrund vorheriger Fehler
image/get_file_from_image: Zeile 109: [: -eq: Einstelliger (unärer) Operator erwartet.
image/get_file_from_image: Zeile 138: [: 0: Einstelliger (unärer) Operator erwartet.
tar: ./var/remote/var/tmp/kernel.image\n./var/remote/var/tmp/x86/kernel.image: Nicht im Archiv gefunden.
tar: Beende mit Fehlerstatus aufgrund vorheriger Fehler
image/get_file_from_image: Zeile 109: [: -eq: Einstelliger (unärer) Operator erwartet.
image/get_file_from_image: Zeile 138: [: 0: Einstelliger (unärer) Operator erwartet.
tar: ./var/remote/var/tmp/filesystem.image\n./var/remote/var/tmp/x86/filesystem.image: Nicht im Archiv gefunden.
tar: Beende mit Fehlerstatus aufgrund vorheriger Fehler
image/get_file_from_image: Zeile 109: [: -eq: Einstelliger (unärer) Operator erwartet.
image/get_file_from_image: Zeile 138: [: 0: Einstelliger (unärer) Operator erwartet.
```

**Comment by PeterPawn** [comment]
Das Skript funktioniert nicht für eine 6490 ... erstens verwendet die kein "ext2"-Image beim Starten aus dem Speicher und zweitens ist das notwendige Vorgehen zum Starten der 6490 aus dem Speicher noch kein "Allgemeingut". 

Die vorhandenen Skripte funktionieren ausschließlich für VR9-Boxen, weil nur der Kernel dort mit den Pseuso-SquashFS-Images von AVM (das sind ext2-Images mit einem 256-Byte-Header, der die SquashFS-Signatur enthält) klarkommt und die Skripte auch noch keine "echten" SquashFS-Images (wie sie z.B. für die GRX-Modelle erforderlich sind) erzeugen (da wäre das Starten aus dem Speicher dann wieder möglich).

Um die 6490 zu modifizieren, muß man nur das x86-Dateisystem entpacken, ändern und neu packen, bevor man es über den Bootloader installiert. Das FS verwendet auch noch LE-Speicherung und ist damit mit den "üblichen Tools" (also dem "mksquashfs" aus den SquashFS-Tools 4.3, die der verwendeten Distro garantiert auch zur Verfügung stehen) zu behandeln.

Das notwendige Binary für SIAB auf x86 gibt es im yf_bin-Repo - man muß also nur noch das passende Start-Skript zusätzlich einbauen (und natürlich das Binary) und kann dann das eigene Image ganz normal über den Bootloader installieren lassen ... solange man die richtige Version für die anderen drei Partitionen in einem Set verwendet, reicht auch der Austausch dieser einzelnen Partition.

Dauer mit einem passenden Linux-System: max. 15 Minuten in Handarbeit - das Packen braucht die meiste Zeit, weil man sich das Start-Skript tatsächlich aus dem Repo hier abkupfern kann.

**Comment by YannisHeine** [comment]
Okay, leider bin ich nicht so tief in der Materie drinne... hättest du eventuell detailliertere Informationen wie man das ganze modifizieren kann ? Ansonsten muss ich wohl mit dem standardfritzOS leben ...
