### ISSUE TITLE
Installation via EVA-FTP-Client.ps1 not working

### ISSUE THREAD

**Issue by zandercodes** [PeterPawn/YourFritz#21]
Hey, I have a problem with install freetz via NAND mode to FRITZ!Box 7590.

Windows Power Shell say: Unexpected answer '' from remote host.

I don't know why.

Sry for my bad english.

Best regards
ZanderCodes

P.S. My FRITZ!Box has the version 7.11

**Comment by PeterPawn** [comment]
Try to re-run the script with "-Verbose" and "-Debug" switches, to get further info which action raises this error (and show the produced output).

But as a first step ... please make absolutely sure, you're using the latest PowerShell (release) version (at least 5.1).

**Comment by zandercodes** [comment]
I have install powershell 5.1.18362.145 on Windows 10 Ver.1903Add -Verbose and -Debug I have the same error: Unexpected answer ‘‘ from remote host.
    	
    	

    	Mit freundlichen GrüßenJulian Zander
    
  




On Thu, Jun 27, 2019 at 9:13 PM +0200, "YourFritz" <notifications@github.com> wrote:












Try to re-run the script with "-Verbose" and "-Debug" switches, to get further info which action raises this error (and show the produced output).


But as a first step ... please make absolutely sure, you're using the latest PowerShell (release) version (at least 5.1).

**Comment by zandercodes** [comment]
Im IPPF FTP bin ich.
Mit dem EVA-Discover.ps1 bin ich dort rein gekommen.
Und wenn ich mit ftp verbinde bekomme ich ADAM2 FTP Server ready zurück.

**Comment by zandercodes** [comment]
Anscheinend ist der Answer leer..
Hab eine Write-Output $answer rein gemacht in Zeile 630 und nicht kommt zurück

**Comment by zandercodes** [comment]
Hab den Fehler gefunden..
In Zeile 629 ist der ReadAnswer zu langsam und das wegen ist es leer.
Wenn ich im Bug eine Zeile darunter eine BreakPoint setzt dann hat es geklappt.
Dort muss wie ein sleep rein.

**Comment by PeterPawn** [comment]
> In Zeile 629 ist der ReadAnswer zu langsam und das wegen ist es leer.

Wenn, dann kann das ja höchstens zu schnell sein. Klingt für mich aber nach einem eher exotischen Problem, das ich auch von anderen bisher noch nicht gehört habe.

Ich tippe hier eher wieder auf irgendeine obskure "security suite", die ihrerseits dazu beiträgt, daß die Daten von der Box erst "nach gründlicher Prüfung" durchgelassen werden und daher die bereits eingebaute Verzögerung von 0,1 Sekunden vor dem Lesen der Antwort im Control-Channel nicht ausreicht.

Das ist aber vermutlich eher ein Problem des verwendeten Rechners und daher mache ich hier zu ... zumal es ja bei Dir offenbar - und sei es halt mit dem Breakpoint - dann doch noch funktioniert hat.
