### ISSUE TITLE
juis_check: No newer version found, check was made with source version '141.06.51-34089'

### ISSUE THREAD

**Issue by macross5** [PeterPawn/YourFritz#22]
I get the message "juis_check: No newer version found, check was made with source version '141.06.51-34089'."

With...

debug: Name="FRITZ!Box 6490 Cable"
debug: HW="213"
debug: OEM="avm"
debug: Lang="de"
debug: Annex="Kabel"
debug: Country="049"
debug: Serial=removed
debug: Major="141"
debug: Minor="6"
debug: Patch="51"
debug: Buildnumber="34089"
debug: Flag=""
debug: Public="1"
debug: type="1001"
debug: hostname="213.jws.avm.de"

The person in https://github.com/PeterPawn/YourFritz/issues/19 wrote a similar Notification but I still get it on the newest version.

I startet the script on android, connected with wlan to the fritzbox who got the Internet from Lan 1.

Thank you!

**Comment by PeterPawn** [comment]
This is obviously no retail device (or it seems not to be one) ... if it's from a provider, the JUIS of AVM does not provide information about updates.

**Comment by macross5** [comment]
I used the JUIS Excel and only changed my current firmware version to a higher version.   After that, I got the download link.

**Comment by PeterPawn** [comment]
Maybe the Excel version adds the needed flag "cable_retail" automatically to a 6490 device. If you specify it yourself (Flags="cable_retail") while calling "juis_check", it will find this version, too. But as you may see above, your running system doesn't provide this flag via its "juis_boxinfo.xml" -> it's not a retail box (or better: there's currently no retail firmware installed).
