### ISSUE TITLE
avm_kernel_config.extract & 4020

### ISSUE THREAD

**Issue by fda77** [PeterPawn/YourFritz#24]
Größe der config-area kann für FRITZ.Box_4020.de-en-es-it-fr-pl.147.07.01.image nicht ermittelt werden

```
 $FTOOLS/avm_kernel_config.extract -l 0x80060000 kernel.raw.unpacked
Unexpected config area content found, extraction aborted.

 $FTOOLS/avm_kernel_config.extract -s 1024 -l 0x80060000 kernel.raw.unpacked
Unexpected config area content found, extraction aborted.

 $FTOOLS/avm_kernel_config.extract -s 64 -l 0x80060000 kernel.raw.unpacked |wc -l
5
```

**Comment by PeterPawn** [comment]
Die in Freetz und "freetz-ng" verwendete Implementierung von `avm_kernel_config` hat meines Wissens mit der meinigen nicht mehr viel gemein.

Ich habe aber auch keine 4020 ... und ich habe (zumindest derzeit) keine Absicht, die Prinziplösung noch einmal anzufassen.

Hier wäre also Freetz (https://github.com/Freetz/freetz/tree/master/tools/make/yourfritz-akc-host/src) die richtige Anlaufstelle ... dort werden eigene Quelldateien (inline source) verwendet.

Daher mache ich hier zu ... außer es gibt gewichtige Gründe, warum das nicht direkt in Freetz geändert werden kann/soll.

**Comment by kamasudo** [comment]
Sorry, hab nicht genau geschaut war da jetzt wirklich was geschrieben hat, durch yourfritz (offiziell YourFritz..) im Verzeichnisnamen ging ich von dir aus. 
Dort hab hab ich aber keine Lust ein Issue zu öffnen. Ich wecke womöglich noch einen Maintainer aus dem Winterschlaf, der mich dann wieder abwürgen muss.
Es hat sich jetzt übrigens herausgestellt, dass es 9 Geräte betrifft (in er13's Fork nicht so viele, da dort noch Geräte fehlen), alle mit Kernel 4.4.60

**Comment by fda77** [comment]
Sorry, hab nicht genau geschaut war da jetzt wirklich was geschrieben hat, durch yourfritz (offiziell YourFritz..) im Verzeichnisnamen ging ich von dir aus.
Dort hab hab ich aber keine Lust ein Issue zu öffnen. Ich wecke womöglich noch einen Maintainer aus dem Winterschlaf, der mich dann wieder abwürgen muss.
Es hat sich jetzt übrigens herausgestellt, dass es 9 Geräte betrifft (in er13's Fork nicht so viele, da dort noch Geräte fehlen), alle mit Kernel 4.4.60
