### ISSUE TITLE
7490 labor firmware shell-in-a-box

### ISSUE THREAD

**Issue by jekkos** [PeterPawn/YourFritz#27]
Hi again!

After doing a succesful mod with shell-in-a-box on my 7490 with firmware `FRITZ.Box_7490.en-de-es-it-fr-pl.113.07.01`, I found that my modem was updated by the ISP with the `FRITZ.Box_7490-07.19-77201-Labor.image` firmware and so I lost access to the shell.

I was trying to reinstall the shell-in-a-box on this labor firmware using the latest script versions but to no avail. Do you know whether something was changed in that firmware that disables the shell-in-a-box startup? I also tried to flash the original 113.07.01 mod (which certainly worked before), but got nothing running on port 8010. Perhaps I need to downgrade the fritzbox to the older firmware.

I used the following command to do the flash when the bootloader starts (usnig bash here as the scripts don't work from zsh)

`(bash ./eva_discover INTERFACE=enp0s31f6 TO=192.168.178.1 FROM=192.168.178.20 BLIP=0) && bash -x ./eva_to_memory 7490.img 192.168.178.1` 

It seems to accept the image happily and then boots after. Find the log here attached.

[log.txt](https://github.com/PeterPawn/YourFritz/files/4563960/log.txt)

**Comment by jekkos** [comment]
Update: I read a bit further here and I might not have had the correct binary versions in the /bin submodule. I have synced the module with the commit hash that is in the main repo and have regenerated the image. Still no success on port 8010.

[log2.txt](https://github.com/PeterPawn/YourFritz/files/4564089/log2.txt)
[imgbuild.txt](https://github.com/PeterPawn/YourFritz/files/4564101/imgbuild.txt)

**Comment by PeterPawn** [comment]
Version 07.19 uses a completely different system start approach and got many more changes.

You may continue reading here: https://www.ip-phone-forum.de/threads/unter-die-haube-geschaut-%C3%84nderungen-neuigkeiten-im-fritz-os-der-labor-reihe-07-19.305167/

There isn't any script yet, that may be used with this version.

You may try to use [modfs](https://github.com/PeterPawn/modfs) for updating to 07.19 from an older version - it will (in the current beta version, which gets published as release in the next few days - try yourfritz.de/modfs-0.6.0-beta.tgz as name of the tarball today) install a telnet instance or you may use your own scripts (or manual changes) to install a "shell in a box" service yourself. The provided binaries (from [yf_bin](https://github.com/PeterPawn/yf_bin)) are linked statically and may be used with 07.19 version, too.

Please use the IPPF board for further discussions - I'll close this as an "issue" now. Feel free to re-open, if there's something wrong with the scripts for versions prior to 07.19.

**Comment by PeterPawn** [comment]
OK, I'll re-open this one myself ... I'll prepare a new version of the SIAB implant script, which covers 07.19+ versions, too, and later I'll close this issue with the commit, which provides these changes.

**Comment by PeterPawn** [comment]
You could try the new version ... there's a pre-built image for a 7490 model: https://github.com/PeterPawn/first_aid/blob/master/implant_siab_3.10.107.image.7490

It uses a 07.12 version by AVM as source, 'cause it doesn't matter, which version is used to add data to the YAFFS2 partition. The installed script to add an own service during startup should handle 07.19 versions successfully now (it did it for me).

**Comment by jekkos** [comment]
OK great! this one works. Thanks for the pointer.
