### ISSUE TITLE
bootmanager: sed in Variable

### ISSUE THREAD

**Issue by fda77** [PeterPawn/YourFritz#30]
Könntest du `sed` am Anfang des Scriptes in einer Variable definieren?
Also `SED=${SED:-sed}`. Dies würde diesen Patch überflüssig machen, der eh früher oder später nicht mehr passen wird: https://github.com/freetz-ng/freetz-ng/commit/d88e97533
Die globale Definition ist hier: https://github.com/Freetz-NG/freetz-ng/blob/master/fwmod#L185
Es geht nur um das sed das auf dem Host im fakeroot-Context ausgeführt wird, da es mit selinux Probleme gibt

**Comment by PeterPawn** [comment]
solved in https://github.com/PeterPawn/YourFritz/commit/829003a5b37e9658c35d3b5df7f3e60b320f1bdb
