### ISSUE TITLE
juis_check: better handling of "BuildType"

### ISSUE THREAD

**Issue by PeterPawn** [PeterPawn/YourFritz#33]
Seems like AVM is checking the `BuildType` field of a request more strictly/thoroughly - I've got problems to get a correct response for a 6490 device, while using a build type of `1001` with a version number of `141.07.02`. Only with the value `1` I've got the expected answer.

Meanwhile some of the used `BuildType` values are well-known (it may be read from `/etc/init.d/rc.conf`) and the script should provide an option to select the wanted "flavor" of firmware, beside the simple differentiation between public and internal versions.

**Comment by fda77** [comment]
Would be great to allow to set `Buildtype=` 'plain' as a parameter, like Annex, Flags etc
Afaik it is not possible to set `Buildtype=1` atm

**Comment by PeterPawn** [comment]
Some thoughts about may be found here: https://github.com/PeterPawn/YourFritz/discussions/36#discussioncomment-326425
