### ISSUE TITLE
Webseite läuft nicht

### ISSUE THREAD

**Issue by fda77** [PeterPawn/YourFritz#55]
Geht net: https://yourfritz.de/

**Comment by PeterPawn** [comment]
Bekannt, Zertifikat ist abgelaufen und muß bei Gelegenheit erneuert werden. Aber das mache ich erst, wenn ich die Dienste alle auf einen neuen Server umgezogen habe - daran laviere ich schon seit längerem. Dauert also noch eine Weile, gibt aber auf der Webseite - außer Redirections - auch nichts Wichtiges.

**Comment by fda77** [comment]
Okay, ich hab den Link auf http geändert. Letsencrypt mit Certbot (oder acme.sh für dns-wildcard) kommt nicht in Frage?
Hast du irgendwo ne Übersicht welche Links es da gibt? Vielleicht ist da noch was für https://freetz-ng.github.io/freetz-ng/INSTALL#ram dabei.

**Comment by PeterPawn** [comment]
Zertifikat erneuert (außerplanmäßig), damit sollten auch HTTPS-Links wieder klaglos funktionieren.

**Comment by fda77** [comment]
Habs angepasst, http vermeide ich soweit möglich. Wieder kein Letsencrypt? Naja. Wie gesagt, wenn auf der ISTALL Seite irgend welche Script von dir noch verlink werden sollen, sag bescheid
